import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/main/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>All Links | Share with friends</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-row">
        <Navbar />

        {/* <Image
          className="svg"
          src="/assets/icons/edit-2-svgrepo-com.svg"
          width="24"
          height="24"
          alt="edit svg icon"
        ></Image> */}
      </main>
    </div>
  );
}
